backend:
  name: github
  repo: yy0534105830-source/news
  branch: main
  # השורה הזו היא הקסם - היא אומרת למערכת לא לחפש שרת חיצוני
  auth_type: implicit 

display_url: https://yy0534105830-source.github.io/news/
media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "כתבות JDN"
    folder: "content/blog"
    create: true
    fields:
      - { label: "כותרת", name: "title", widget: "string" }
      - { label: "תמונה", name: "image", widget: "image" }
      - { label: "מיקום (top/side/ticker)", name: "layout_position", widget: "string", default: "side" }
      - { label: "תוכן", name: "body", widget: "markdown" }
