backend:
  name: github
  repo: yy0534105830-source/news
  branch: main
  auth_type: implicit
  app_id: Ov23liyj2fBKFhjXJGvj
  # התיקון כאן: הוספת הקישור הישיר בצורה שהמערכת לא תנסה "להדביק" לו את כתובת האתר
  auth_endpoint: https://github.com/login/oauth/authorize

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "כתבות"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "כותרת", name: "title", widget: "string" }
      - { 
          label: "מיקום", 
          name: "layout_position", 
          widget: "select", 
          options: [
            { label: "ראשית", value: "top" },
            { label: "ריבוע", value: "side" },
            { label: "מבזק", value: "ticker" }
          ] 
        }
      - { label: "תמונה", name: "image", widget: "string", required: false }
      - { label: "תוכן", name: "body", widget: "markdown" }
